export const SAMPLE_DATA: any = [
  {
    artistPair: 'Mike Jones-Waka Flocka Flame',
    genres: ['dirty south rap', 'gangster rap', 'hip hop', 'pop rap', 'rap', 'southern hip hop', 'trap music'],
  },
  {
    artistPair: 'Mike Jones-Young Buck',
    genres: ['dirty south rap', 'gangster rap', 'hip hop', 'pop rap', 'rap', 'southern hip hop', 'trap music'],
  },
  {
    artistPair: 'Mike Jones-Young Money',
    genres: ['dirty south rap', 'gangster rap', 'hip hop', 'pop rap', 'rap', 'southern hip hop', 'trap music'],
  },
  {
    artistPair: 'Waka Flocka Flame-Young Buck',
    genres: ['dirty south rap', 'gangster rap', 'hip hop', 'pop rap', 'rap', 'southern hip hop', 'trap music'],
  },
  {
    artistPair: 'Waka Flocka Flame-Young Money',
    genres: ['dirty south rap', 'gangster rap', 'hip hop', 'pop rap', 'rap', 'southern hip hop', 'trap music'],
  },

  {
    artistPair: 'Young Buck-Young Money',
    genres: ['dirty south rap', 'gangster rap', 'hip hop', 'pop rap', 'rap', 'southern hip hop', 'trap music'],
  },



  {
    artistPair: 'Big Pun-Young Buck',
    genres: ['gangster rap', 'hardcore hip hop', 'hip hop', 'pop rap', 'rap', 'southern hip hop'],
  },

  { artistPair: 'Tego Calderon-Yandel', genres: ['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'tropical'] },
  { artistPair: 'Big Pun-Mike Jones', genres: ['gangster rap', 'hip hop', 'pop rap', 'rap', 'southern hip hop'] },
  { artistPair: '50 Cent-Big Pun', genres: ['east coast hip hop', 'gangster rap', 'hip hop', 'pop rap', 'rap'] },
  { artistPair: 'Lil Wayne-Young Money', genres: ['hip hop', 'pop', 'pop rap', 'rap', 'trap music'] },
  {
    artistPair: 'Big Pun-Waka Flocka Flame',
    genres: ['gangster rap', 'hip hop', 'pop rap', 'rap', 'southern hip hop'],
  },
  { artistPair: 'Big Pun-Young Money', genres: ['gangster rap', 'hip hop', 'pop rap', 'rap', 'southern hip hop'] },
  { artistPair: 'Plan B-Yandel', genres: ['latin', 'reggaeton', 'reggaeton flow', 'tropical'] },
  { artistPair: 'Don Omar-Yandel', genres: ['latin', 'latin hip hop', 'reggaeton', 'tropical'] },
  { artistPair: 'Antonio Aguilar-Chalino Sanchez', genres: ['banda', 'grupera', 'norteno', 'regional mexican'] },
  { artistPair: 'Antonio Aguilar-Los Tucanes De Tijuana', genres: ['banda', 'grupera', 'norteno', 'regional mexican'] },
  { artistPair: 'Chalino Sanchez-Los Tucanes De Tijuana', genres: ['banda', 'grupera', 'norteno', 'regional mexican'] },
  { artistPair: '50 Cent-Mike Jones', genres: ['gangster rap', 'hip hop', 'pop rap', 'rap'] },
  { artistPair: 'Lil Wayne-Mike Jones', genres: ['hip hop', 'pop rap', 'rap', 'trap music'] },
  { artistPair: '50 Cent-Waka Flocka Flame', genres: ['gangster rap', 'hip hop', 'pop rap', 'rap'] },
  { artistPair: '50 Cent-Young Buck', genres: ['gangster rap', 'hip hop', 'pop rap', 'rap'] },
  { artistPair: '50 Cent-Young Money', genres: ['gangster rap', 'hip hop', 'pop rap', 'rap'] },
  { artistPair: 'Plan B-Tego Calderon', genres: ['latin', 'reggaeton', 'reggaeton flow', 'tropical'] },
  { artistPair: 'Don Omar-Tego Calderon', genres: ['latin', 'latin hip hop', 'reggaeton', 'tropical'] },
  { artistPair: 'Lil Wayne-Waka Flocka Flame', genres: ['hip hop', 'pop rap', 'rap', 'trap music'] },
  { artistPair: 'Lil Wayne-Young Buck', genres: ['hip hop', 'pop rap', 'rap', 'trap music'] },
  { artistPair: 'Antonio Aguilar-Los Socios Del Ritmo', genres: ['grupera', 'ranchera', 'regional mexican'] },
  { artistPair: '50 Cent-Lil Wayne', genres: ['hip hop', 'pop rap', 'rap'] },
  { artistPair: 'Don Omar-Plan B', genres: ['latin', 'reggaeton', 'tropical'] },
  { artistPair: 'Big Pun-Lil Wayne', genres: ['hip hop', 'pop rap', 'rap'] },
  { artistPair: 'Chalino Sanchez-Los Socios Del Ritmo', genres: ['grupera', 'regional mexican'] },
  { artistPair: 'Los Socios Del Ritmo-Los Tucanes De Tijuana', genres: ['grupera', 'regional mexican'] },
  { artistPair: 'Eminem-Mike Jones', genres: ['hip hop', 'rap'] },
  { artistPair: '50 Cent-Eminem', genres: ['hip hop', 'rap'] },
  { artistPair: 'Eminem-Lil Wayne', genres: ['hip hop', 'rap'] },
  { artistPair: 'Eminem-Waka Flocka Flame', genres: ['hip hop', 'rap'] },
  { artistPair: 'Big Pun-Eminem', genres: ['hip hop', 'rap'] },
  { artistPair: 'Eminem-Young Buck', genres: ['hip hop', 'rap'] },
  { artistPair: 'Eminem-Young Money', genres: ['hip hop', 'rap'] },
  { artistPair: 'Lil Wayne-Yandel', genres: ['pop'] },
  { artistPair: 'Yandel-Young Money', genres: ['pop'] },
  { artistPair: 'Mike Jones-Paul Rosenberg', genres: ['hip hop'] },
  { artistPair: '50 Cent-Paul Rosenberg', genres: ['hip hop'] },
  { artistPair: 'Eminem-Paul Rosenberg', genres: ['hip hop'] },
  { artistPair: 'Lil Wayne-Paul Rosenberg', genres: ['hip hop'] },
  { artistPair: 'Paul Rosenberg-Waka Flocka Flame', genres: ['hip hop'] },
  { artistPair: 'Big Pun-Paul Rosenberg', genres: ['hip hop'] },
  { artistPair: 'Paul Rosenberg-Young Buck', genres: ['hip hop'] },
  { artistPair: 'Paul Rosenberg-Young Money', genres: ['hip hop'] },
  { artistPair: 'Ancient Astronauts-Aphex Twin', genres: ['trip hop'] },
];
